### ISSUE TITLE
Hindi glossary

### ISSUE THREAD

**Issue by arshadkazmi42** [gatsbyjs/gatsby-hi#3]
Adding a list of commonly used translations

| Term | Translation |
| :---: | :---:|
| App | एप्प |
| Apps | ऍप्स |
| Javascript | जावास्क्रिप्ट |
| Tutorial | ट्यूटोरियल |
| Text | टेक्स्ट |
| Value | वैल्यू  |
| View | व्यू |

Content that does not need to be translated:

| No translation required |
| :-----: |
| API |
| array |
| class |
| constructor |
| context |
| CDN |
| HTML |
| props |
| strings |
| UI |
| key |

**Comment by arshadkazmi42** [comment]
Feel free to comment suggestions here, we will keep updating the list

**Comment by arshadkazmi42** [comment]
Just checked, we have a style-guide. Let's move these in there.

**Comment by KiranAkadas** [comment]
Need help?

**Comment by arshadkazmi42** [comment]
@KiranAkadas We already have a PR for this. Thanks
